= How Version 4.x Differs from Previous Versions

Scripts that use versions of the Anypoint Platform CLI earlier than 4.x do not automatically use Anypoint CLI 4.x commands because the new version of the CLI has different command names and syntax. However, because the CLI version 4.x name and install package are different from previous versions, you can install Anypoint CLI 4.x and an earlier version on the same system and use both versions in your scripts. 

Warning: Anypoint CLI 4.x is not backward compatible with previous versions.

== Changes

Anypoint CLI 4.x introduces the following changes:

* *CLI Name* The new CLI is named `anypoint-cli-v4`. 
* *Installation* Command groups for Anypoint Platform components are packaged as plugins that can optionally be installed and uninstalled separately from the core installation package.
* *Authentication* 
** Set your credentials using the `anypoint-cli-v4 conf` command. +
** The only way to authenticate to Anypoint CLI 4.x is through xref:access-management::connected-apps-overview.adoc[Connected Apps].
* *Command Syntax* The separator between command parameters can be either a colon (:) or a space. For example, the command to get the Exchange asset resource list can be either `anypoint-cli-v4 exchange:asset:resource:list` or `anypoint-cli-v4 exchange asset resource list`.

* *Commands and Properties* The following commands and properties have changed:

 ** `exchange:asset:upload` replaces `exchange:asset:uploadv2`.
 ** `exchange:asset:upload --properties='{"property1":"value2", "property2": "value2"}'` replaces `exchange:asset:upload properties.value1.value2`.
 ** `cloudhub:load-balancer:allowlist:add/remove` commands replace the similar commands that used a non-inclusive term.
 ** `runtime-mgr:cloudhub-application:describe -o JSON` replaces `runtime-mgr cloudhub-application describe-json`.
 ** `runtime-mgr:pcf-application:describe -o JSON` replaces `runtime-mgr pcf-application describe-json`.
 ** `cloudhub:vpc:describe -o JSON` replaces `cloudhub vpc describe-json`.
 ** Environments and Business Groups commands are no longer supported.
 ** Datagraph API Source Management commands are no longer supported.
 ** Runtime Fabric Instances commands are no longer supported. 

* *Interactive Mode* Because interactive mode is no longer supported, the following commands and flags are no longer available:

 ** `use business-group` command
 ** `use environment` command
 ** `exit` command
 ** `-f, --fields` flag
 ** Ability to interactively enter the password if you omit it

*When using multi-option flags in a command in Anypoint CLI 4.x,you need to either put the parameter before the flags or use a `-- ` (two dashes followed by a space) before the parameter to make it work.
