= Local Server Groups

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|xref:anypoint-cli::server-groups.adoc#runtime-mgr-servergroup-add-server[runtime-mgr:serverGroup:add:server] | Adds server to a server group
|xref:anypoint-cli::server-groups.adoc#runtime-mgr-servergroup-create[runtime-mgr:serverGroup:create] | Creates server group from servers
|xref:anypoint-cli::server-groups.adoc#runtime-mgr-servergroup-describe[runtime-mgr:serverGroup:describe] | Describes server group
|xref:anypoint-cli::server-groups.adoc#runtime-mgr-servergroup-delete[runtime-mgr:serverGroup:delete] | Deletes server group
|xref:anypoint-cli::server-groups.adoc#runtime-mgr-servergroup-list[runtime-mgr:serverGroup:list] | Lists all server groups in the environment
|xref:anypoint-cli::server-groups.adoc#runtime-mgr-servergroup-modify[runtime-mgr:serverGroup:modify] | Modifies server group
|xref:anypoint-cli::server-groups.adoc#runtime-mgr-servergroup-remove-server[runtime-mgr:serverGroup:remove:server] | Removes server from a server group
|===

// end::summary[]

// tag::commands[]

[[runtime-mgr-servergroup-add-server]]
== runtime-mgr:serverGroup:add:server

----
> runtime-mgr:serverGroup:add:server [flags] <serverGroupId> <serverId>
----

Adds the server passed in `serverId` to the server group passed in `serverGroupId`.

This command accepts the xref:index.adoc#default-options[default flags].

[[runtime-mgr-servergroup-create]]
== runtime-mgr:serverGroup:create

----
> runtime-mgr:serverGroup:create [flags] <name> [serverIds...]
----

Creates a server group with the name passed in `name` using the server Id(s) passed as argument(s) thereafter.

This command accepts the xref:index.adoc#default-options[default flags].

[[runtime-mgr-servergroup-describe]]
== runtime-mgr:serverGroup:describe

----
> runtime-mgr:serverGroup:describe [flags] <serverGroupId>
----

Describes the server group passed in `serverGroupId`.

This command accepts the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command accepts the xref:index.adoc#default-options[default flags].

[[runtime-mgr-servergroup-delete]]
== runtime-mgr:serverGroup:delete

----
> runtime-mgr:serverGroup:delete [flags] <serverGroupId>
----

Deletes the server groups passed in `serverGroupId`.

This command accepts the xref:index.adoc#default-options[default flags].

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

[[runtime-mgr-servergroup-list]]
== runtime-mgr:serverGroup:list

----
> runtime-mgr:serverGroup:list [flags]
----

Lists all server groups in the environment.

This command has the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command accepts the xref:index.adoc#default-options[default flags].

[[runtime-mgr-servergroup-modify]]
== runtime-mgr:serverGroup:modify

----
> runtime-mgr:serverGroup:modify [flags] <serverGroupId>
----

Modifies the server group passed in `serverGroupId`.

In order to update the id for the cluster, you need to pass the  `--name` flag.

This command accepts the xref:index.adoc#default-options[default flags].

[[runtime-mgr-servergroup-remove-server]]
== runtime-mgr:serverGroup:remove:server

----
> runtime-mgr:serverGroup:remove:server [flags] <serverGroupId> <serverId>
----

Removes the server passed in `serverId` from the server group passed in `serverGroupId`.

This command accepts the xref:index.adoc#default-options[default flags].

// end::commands[]
